language: java
jdk:
  - openjdk8
script:
  - sudo /usr/local/maven/bin/mvn clean package
cache:
  directories:
    - $HOME/.m2
deploy:
  provider: heroku
  app: tinder-step-danit
  api_key:
    secure: $HEROKU_API_KEY
