language: java
jdk:
  - opendk8
before_script:
  - echo "Starting build"
script:
  - mvn clean package
after_script:
  - echo "Script finished"
after_success:
  - echo "Build was successful. $TRAVIS_TEST_RESULT"
after_failure:
  - echo "Build was failed"
cache:
  directories:
    - $HOME/.m2
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: tinder-step-danit