language: java
jdk:
  - openjdk8
script:
  - mvn clean package
cache:
  directories:
    - $HOME/.m2
deploy:
  provider: heroku
  app: tinder-step-danit
  on:
    branch: master
  api_key:
    secure: $HEROKU_API_KEY
